// Auto-generated by scripts/build_web_dashboard_data.py
window.REEFSAFE_DATA = {
  "nationalKPIs": {
    "latestMeanCoralCover": 39.8185,
    "latestSurveyYear": 2025,
    "pairedChange2024To2025": -4.758717948717937,
    "pairedUnits": 39,
    "priorityCount": 10,
    "surveyedUnits": 40
  },
  "priorityIslands": [
    {
      "rank": 1,
      "island": "Labuan",
      "state": "W.P. Labuan",
      "ecoregion": "North Borneo",
      "lat": 5.3167,
      "lng": 115.2167,
      "marinePark": "Labuan Marine Park",
      "surveyYear": 2025,
      "lcc": 24.23,
      "lccChangeRate": -7.345,
      "dhwContext": 4.04,
      "predictedNextChange": -14.417288249580414,
      "predictionLower": -30.67167372568418,
      "predictionUpper": -0.7552712902505725,
      "tier": "High screening priority",
      "sourceConfidence": "PDF geometry only - not cross-checked",
      "evidence": "NOAA thermal stress observed",
      "nextStep": "Coordinate bleaching survey; do not attribute thermal loss to visitors"
    },
    {
      "rank": 2,
      "island": "Kapas",
      "state": "Terengganu",
      "ecoregion": "Sunda Shelf",
      "lat": 5.2167,
      "lng": 103.2667,
      "marinePark": "Terengganu Marine Park",
      "surveyYear": 2025,
      "lcc": 52.63,
      "lccChangeRate": 5.11,
      "dhwContext": 2.05,
      "predictedNextChange": -5.751054835884399,
      "predictionLower": -22.005440311988163,
      "predictionUpper": 7.910962123445443,
      "tier": "High screening priority",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Modelled decline; no single dominant observed stressor",
      "nextStep": "Prioritise field validation before imposing restrictions"
    },
    {
      "rank": 3,
      "island": "Seri Buat",
      "state": "Pahang",
      "ecoregion": "Sunda Shelf",
      "lat": 2.6833,
      "lng": 104.1333,
      "marinePark": "Tioman Marine Park Buffer",
      "surveyYear": 2025,
      "lcc": 54.22,
      "lccChangeRate": -7.84,
      "dhwContext": 2.05,
      "predictedNextChange": -5.154702883712362,
      "predictionLower": -21.409088359816124,
      "predictionUpper": 8.50731407561748,
      "tier": "High screening priority",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Anchor impact mentioned in Reef Check report",
      "nextStep": "Inspect mooring availability and anchoring controls"
    },
    {
      "rank": 4,
      "island": "Mertang",
      "state": "Johor",
      "ecoregion": "Sunda Shelf",
      "lat": 2.46,
      "lng": 103.98,
      "marinePark": "Mersing Marine Park",
      "surveyYear": 2025,
      "lcc": 58.33,
      "lccChangeRate": -11.25,
      "dhwContext": 1.88,
      "predictedNextChange": -5.0266139003205,
      "predictionLower": -21.280999376424262,
      "predictionUpper": 8.635403059009342,
      "tier": "High screening priority",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Anchor impact mentioned in Reef Check report",
      "nextStep": "Inspect mooring availability and anchoring controls"
    },
    {
      "rank": 5,
      "island": "Mensirip",
      "state": "Johor",
      "ecoregion": "Sunda Shelf",
      "lat": 2.45,
      "lng": 103.95,
      "marinePark": "Mersing Marine Park",
      "surveyYear": 2025,
      "lcc": 54.17,
      "lccChangeRate": -4.66,
      "dhwContext": 1.88,
      "predictedNextChange": -4.849858937927289,
      "predictionLower": -21.10424441403105,
      "predictionUpper": 8.812158021402553,
      "tier": "High screening priority",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Waste or pollution indicator is elevated",
      "nextStep": "Inspect waste and wastewater controls"
    },
    {
      "rank": 6,
      "island": "Tenggol",
      "state": "Terengganu",
      "ecoregion": "Sunda Shelf",
      "lat": 4.8,
      "lng": 103.6833,
      "marinePark": "Terengganu Marine Park",
      "surveyYear": 2025,
      "lcc": 54.17,
      "lccChangeRate": -2.91,
      "dhwContext": 2.05,
      "predictedNextChange": -4.639589454718053,
      "predictionLower": -20.893974930821816,
      "predictionUpper": 9.022427504611787,
      "tier": "High screening priority",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Waste or pollution indicator is elevated",
      "nextStep": "Inspect waste and wastewater controls"
    },
    {
      "rank": 7,
      "island": "Tinggi",
      "state": "Johor",
      "ecoregion": "Sunda Shelf",
      "lat": 2.3,
      "lng": 104.1167,
      "marinePark": "Mersing Marine Park",
      "surveyYear": 2025,
      "lcc": 52.5,
      "lccChangeRate": -4.22,
      "dhwContext": 1.88,
      "predictedNextChange": -4.625227283981603,
      "predictionLower": -20.879612760085365,
      "predictionUpper": 9.036789675348238,
      "tier": "High screening priority",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Anchor impact mentioned in Reef Check report",
      "nextStep": "Inspect mooring availability and anchoring controls"
    },
    {
      "rank": 8,
      "island": "Lima",
      "state": "Johor",
      "ecoregion": "Sunda Shelf",
      "lat": 2.2167,
      "lng": 104.1667,
      "marinePark": "Mersing Marine Park",
      "surveyYear": 2025,
      "lcc": 51.88,
      "lccChangeRate": -10.4,
      "dhwContext": 1.88,
      "predictedNextChange": -4.372997869193041,
      "predictionLower": -20.627383345296806,
      "predictionUpper": 9.2890190901368,
      "tier": "High screening priority",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Anchor impact mentioned in Reef Check report",
      "nextStep": "Inspect mooring availability and anchoring controls"
    },
    {
      "rank": 9,
      "island": "Sibu",
      "state": "Johor",
      "ecoregion": "Sunda Shelf",
      "lat": 2.2167,
      "lng": 104.0667,
      "marinePark": "Mersing Marine Park",
      "surveyYear": 2025,
      "lcc": 52.81,
      "lccChangeRate": 2.08,
      "dhwContext": 1.88,
      "predictedNextChange": -4.3361716781234225,
      "predictionLower": -20.590557154227184,
      "predictionUpper": 9.32584528120642,
      "tier": "High screening priority",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Anchor impact mentioned in Reef Check report",
      "nextStep": "Inspect mooring availability and anchoring controls"
    },
    {
      "rank": 10,
      "island": "Lankayan",
      "state": "Sabah",
      "ecoregion": "North Borneo",
      "lat": 6.5028,
      "lng": 117.9239,
      "marinePark": "Sugud Islands Marine Conservation Area (SIMCA)",
      "surveyYear": 2025,
      "lcc": 51.04,
      "lccChangeRate": 1.51,
      "dhwContext": 4.04,
      "predictedNextChange": -4.073063575373093,
      "predictionLower": -20.327449051476854,
      "predictionUpper": 9.58895338395675,
      "tier": "High screening priority",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "NOAA thermal stress observed",
      "nextStep": "Coordinate bleaching survey; do not attribute thermal loss to visitors"
    },
    {
      "rank": 11,
      "island": "Sipadan",
      "state": "Sabah",
      "ecoregion": "North Borneo",
      "lat": 4.1147,
      "lng": 118.6289,
      "marinePark": "Sipadan Island Park",
      "surveyYear": 2025,
      "lcc": 55.21,
      "lccChangeRate": -8.08,
      "dhwContext": 4.04,
      "predictedNextChange": -4.061045802819757,
      "predictionLower": -20.31543127892352,
      "predictionUpper": 9.600971156510084,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "NOAA thermal stress observed",
      "nextStep": "Coordinate bleaching survey; do not attribute thermal loss to visitors"
    },
    {
      "rank": 12,
      "island": "Tun Sakaran Marine Park",
      "state": "Sabah",
      "ecoregion": "North Borneo",
      "lat": 4.6,
      "lng": 118.7833,
      "marinePark": "Tun Sakaran Marine Park",
      "surveyYear": 2025,
      "lcc": 51.77,
      "lccChangeRate": -4.01,
      "dhwContext": 4.04,
      "predictedNextChange": -3.9730662979087525,
      "predictionLower": -20.227451774012515,
      "predictionUpper": 9.688950661421089,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "NOAA thermal stress observed",
      "nextStep": "Coordinate bleaching survey; do not attribute thermal loss to visitors"
    },
    {
      "rank": 13,
      "island": "Larapan",
      "state": "Sabah",
      "ecoregion": "Sulu Sea",
      "lat": 4.5167,
      "lng": 118.5833,
      "marinePark": "Tun Sakaran Marine Park",
      "surveyYear": 2025,
      "lcc": 50.88,
      "lccChangeRate": -7.62,
      "dhwContext": 4.04,
      "predictedNextChange": -3.4353759847238763,
      "predictionLower": -19.68976146082764,
      "predictionUpper": 10.226640974605965,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "NOAA thermal stress observed",
      "nextStep": "Coordinate bleaching survey; do not attribute thermal loss to visitors"
    },
    {
      "rank": 14,
      "island": "Harimau",
      "state": "Johor",
      "ecoregion": "Sunda Shelf",
      "lat": 2.5083,
      "lng": 103.9317,
      "marinePark": "Mersing Marine Park",
      "surveyYear": 2025,
      "lcc": 48.96,
      "lccChangeRate": -11.31,
      "dhwContext": 1.88,
      "predictedNextChange": -3.1494546809297406,
      "predictionLower": -19.403840157033503,
      "predictionUpper": 10.5125622784001,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Waste or pollution indicator is elevated",
      "nextStep": "Inspect waste and wastewater controls"
    },
    {
      "rank": 15,
      "island": "Tengah",
      "state": "Johor",
      "ecoregion": "Sunda Shelf",
      "lat": 2.47,
      "lng": 103.96,
      "marinePark": "Mersing Marine Park",
      "surveyYear": 2025,
      "lcc": 45.73,
      "lccChangeRate": -2.22,
      "dhwContext": 1.88,
      "predictedNextChange": -3.025109729649479,
      "predictionLower": -19.279495205753243,
      "predictionUpper": 10.636907229680363,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Waste or pollution indicator is elevated",
      "nextStep": "Inspect waste and wastewater controls"
    },
    {
      "rank": 16,
      "island": "Rawa",
      "state": "Johor",
      "ecoregion": "Sunda Shelf",
      "lat": 2.5186,
      "lng": 103.9747,
      "marinePark": "Mersing Marine Park",
      "surveyYear": 2025,
      "lcc": 48.85,
      "lccChangeRate": -7.68,
      "dhwContext": 1.88,
      "predictedNextChange": -2.9055323888925804,
      "predictionLower": -19.159917864996345,
      "predictionUpper": 10.756484570437262,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Waste or pollution indicator is elevated",
      "nextStep": "Inspect waste and wastewater controls"
    },
    {
      "rank": 17,
      "island": "Gual",
      "state": "Johor",
      "ecoregion": "Sunda Shelf",
      "lat": 2.4719,
      "lng": 104.0167,
      "marinePark": "Mersing Marine Park",
      "surveyYear": 2025,
      "lcc": 45.31,
      "lccChangeRate": -10.45,
      "dhwContext": 1.88,
      "predictedNextChange": -2.8399960272108564,
      "predictionLower": -19.09438150331462,
      "predictionUpper": 10.822020932118985,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Waste or pollution indicator is elevated",
      "nextStep": "Inspect waste and wastewater controls"
    },
    {
      "rank": 18,
      "island": "Penyu",
      "state": "Sabah",
      "ecoregion": "Sulu Sea",
      "lat": 6.1667,
      "lng": 118.0667,
      "marinePark": "Turtle Islands National Park",
      "surveyYear": 2025,
      "lcc": 37.77,
      "lccChangeRate": -1.53,
      "dhwContext": 4.04,
      "predictedNextChange": -2.758453602683239,
      "predictionLower": -19.012839078787003,
      "predictionUpper": 10.903563356646602,
      "tier": "Monitor",
      "sourceConfidence": "PDF geometry only - not cross-checked",
      "evidence": "NOAA thermal stress observed",
      "nextStep": "Coordinate bleaching survey; do not attribute thermal loss to visitors"
    },
    {
      "rank": 19,
      "island": "Payar",
      "state": "Kedah",
      "ecoregion": "Malacca Strait",
      "lat": 6.0639,
      "lng": 100.0417,
      "marinePark": "Pulau Payar Marine Park",
      "surveyYear": 2025,
      "lcc": 42.29,
      "lccChangeRate": -6.84,
      "dhwContext": 1.94,
      "predictedNextChange": -2.753521664652438,
      "predictionLower": -19.007907140756203,
      "predictionUpper": 10.908495294677405,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Modelled decline; no single dominant observed stressor",
      "nextStep": "Prioritise field validation before imposing restrictions"
    },
    {
      "rank": 20,
      "island": "Lahad Datu",
      "state": "Sabah",
      "ecoregion": "North Borneo",
      "lat": 5.0167,
      "lng": 118.3333,
      "marinePark": "Darvel Bay Reefs",
      "surveyYear": 2025,
      "lcc": 41.42,
      "lccChangeRate": 5.73,
      "dhwContext": 4.04,
      "predictedNextChange": -2.675723159139596,
      "predictionLower": -18.93010863524336,
      "predictionUpper": 10.986293800190246,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "NOAA thermal stress observed",
      "nextStep": "Coordinate bleaching survey; do not attribute thermal loss to visitors"
    },
    {
      "rank": 21,
      "island": "Tun Mustapha Park",
      "state": "Sabah",
      "ecoregion": "North Borneo",
      "lat": 7.1,
      "lng": 117.15,
      "marinePark": "Tun Mustapha Park",
      "surveyYear": 2025,
      "lcc": 40.35,
      "lccChangeRate": -4.48,
      "dhwContext": 4.04,
      "predictedNextChange": -2.4018311478189034,
      "predictionLower": -18.656216623922667,
      "predictionUpper": 11.260185811510938,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "NOAA thermal stress observed",
      "nextStep": "Coordinate bleaching survey; do not attribute thermal loss to visitors"
    },
    {
      "rank": 22,
      "island": "Hujung",
      "state": "Johor",
      "ecoregion": "Sunda Shelf",
      "lat": 2.4833,
      "lng": 103.9833,
      "marinePark": "Mersing Marine Park",
      "surveyYear": 2025,
      "lcc": 41.77,
      "lccChangeRate": -4.83,
      "dhwContext": 1.88,
      "predictedNextChange": -2.305376552555445,
      "predictionLower": -18.559762028659208,
      "predictionUpper": 11.356640406774396,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Anchor impact mentioned in Reef Check report",
      "nextStep": "Inspect mooring availability and anchoring controls"
    },
    {
      "rank": 23,
      "island": "Pemanggil",
      "state": "Johor",
      "ecoregion": "Sunda Shelf",
      "lat": 2.5833,
      "lng": 104.3167,
      "marinePark": "Mersing Marine Park",
      "surveyYear": 2025,
      "lcc": 43.75,
      "lccChangeRate": -3.75,
      "dhwContext": 1.88,
      "predictedNextChange": -2.2655422927152866,
      "predictionLower": -18.519927768819052,
      "predictionUpper": 11.396474666614555,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Waste or pollution indicator is elevated",
      "nextStep": "Inspect waste and wastewater controls"
    },
    {
      "rank": 24,
      "island": "Besar",
      "state": "Johor",
      "ecoregion": "Sunda Shelf",
      "lat": 2.4333,
      "lng": 103.9667,
      "marinePark": "Mersing Marine Park",
      "surveyYear": 2025,
      "lcc": 43.04,
      "lccChangeRate": 0.63,
      "dhwContext": 1.88,
      "predictedNextChange": -2.211998726662781,
      "predictionLower": -18.466384202766545,
      "predictionUpper": 11.45001823266706,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Anchor impact mentioned in Reef Check report",
      "nextStep": "Inspect mooring availability and anchoring controls"
    },
    {
      "rank": 25,
      "island": "Usukan Cove",
      "state": "Sabah",
      "ecoregion": "North Borneo",
      "lat": 6.3833,
      "lng": 116.4167,
      "marinePark": "West Coast Sabah Coastal",
      "surveyYear": 2025,
      "lcc": 15.94,
      "lccChangeRate": -16.5,
      "dhwContext": 4.04,
      "predictedNextChange": -2.1761258242965917,
      "predictionLower": -18.430511300400354,
      "predictionUpper": 11.485891135033249,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "NOAA thermal stress observed",
      "nextStep": "Coordinate bleaching survey; do not attribute thermal loss to visitors"
    },
    {
      "rank": 26,
      "island": "Port Dickson",
      "state": "Negeri Sembilan",
      "ecoregion": "Malacca Strait",
      "lat": 2.4833,
      "lng": 101.85,
      "marinePark": "Non-Park Fringing Reef",
      "surveyYear": 2025,
      "lcc": 35.01,
      "lccChangeRate": -7.5,
      "dhwContext": 2.05,
      "predictedNextChange": -2.0251321151123203,
      "predictionLower": -18.279517591216084,
      "predictionUpper": 11.636884844217521,
      "tier": "Monitor",
      "sourceConfidence": "PDF geometry only - not cross-checked",
      "evidence": "Anchor impact mentioned in Reef Check report",
      "nextStep": "Inspect mooring availability and anchoring controls"
    },
    {
      "rank": 27,
      "island": "Aur & Dayang",
      "state": "Johor",
      "ecoregion": "Sunda Shelf",
      "lat": 2.4481,
      "lng": 104.5164,
      "marinePark": "Mersing Marine Park",
      "surveyYear": 2025,
      "lcc": 35.42,
      "lccChangeRate": -2.61,
      "dhwContext": 1.88,
      "predictedNextChange": -1.9166614591748918,
      "predictionLower": -18.171046935278657,
      "predictionUpper": 11.74535550015495,
      "tier": "Monitor",
      "sourceConfidence": "PDF geometry only - not cross-checked",
      "evidence": "Anchor impact mentioned in Reef Check report",
      "nextStep": "Inspect mooring availability and anchoring controls"
    },
    {
      "rank": 28,
      "island": "Tioman",
      "state": "Pahang",
      "ecoregion": "Sunda Shelf",
      "lat": 2.7833,
      "lng": 104.1667,
      "marinePark": "Tioman Marine Park",
      "surveyYear": 2025,
      "lcc": 42.99,
      "lccChangeRate": -15.3,
      "dhwContext": 1.88,
      "predictedNextChange": -1.6330955418541313,
      "predictionLower": -17.887481017957896,
      "predictionUpper": 12.028921417475711,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Anchor impact mentioned in Reef Check report",
      "nextStep": "Inspect mooring availability and anchoring controls"
    },
    {
      "rank": 29,
      "island": "Tiga",
      "state": "Sabah",
      "ecoregion": "North Borneo",
      "lat": 5.725,
      "lng": 115.6417,
      "marinePark": "Pulau Tiga National Park",
      "surveyYear": 2025,
      "lcc": 21.52,
      "lccChangeRate": -1.15,
      "dhwContext": 4.04,
      "predictedNextChange": -1.5732425039281994,
      "predictionLower": -17.827627980031963,
      "predictionUpper": 12.088774455401643,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "NOAA thermal stress observed",
      "nextStep": "Coordinate bleaching survey; do not attribute thermal loss to visitors"
    },
    {
      "rank": 30,
      "island": "Rhu",
      "state": "Terengganu",
      "ecoregion": "Sunda Shelf",
      "lat": 5.8167,
      "lng": 102.6167,
      "marinePark": "Terengganu Marine Park",
      "surveyYear": 2025,
      "lcc": 27.92,
      "lccChangeRate": -0.37,
      "dhwContext": 2.05,
      "predictedNextChange": -1.1947556438251963,
      "predictionLower": -17.44914111992896,
      "predictionUpper": 12.467261315504645,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Modelled decline; no single dominant observed stressor",
      "nextStep": "Prioritise field validation before imposing restrictions"
    },
    {
      "rank": 31,
      "island": "Redang",
      "state": "Terengganu",
      "ecoregion": "Sunda Shelf",
      "lat": 5.7667,
      "lng": 103.0167,
      "marinePark": "Terengganu Marine Park",
      "surveyYear": 2025,
      "lcc": 25.89,
      "lccChangeRate": -3.28,
      "dhwContext": 2.05,
      "predictedNextChange": -1.109083024189587,
      "predictionLower": -17.36346850029335,
      "predictionUpper": 12.552933935140254,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Waste or pollution indicator is elevated",
      "nextStep": "Inspect waste and wastewater controls"
    },
    {
      "rank": 32,
      "island": "Perhentian",
      "state": "Terengganu",
      "ecoregion": "Sunda Shelf",
      "lat": 5.9,
      "lng": 102.7333,
      "marinePark": "Terengganu Marine Park",
      "surveyYear": 2025,
      "lcc": 32.44,
      "lccChangeRate": -6.75,
      "dhwContext": 2.05,
      "predictedNextChange": -1.0796533079650468,
      "predictionLower": -17.33403878406881,
      "predictionUpper": 12.582363651364794,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Waste or pollution indicator is elevated",
      "nextStep": "Inspect waste and wastewater controls"
    },
    {
      "rank": 33,
      "island": "Tunku Abdul Rahman Park",
      "state": "Sabah",
      "ecoregion": "North Borneo",
      "lat": 5.9667,
      "lng": 115.9833,
      "marinePark": "Tunku Abdul Rahman Park",
      "surveyYear": 2025,
      "lcc": 13.12,
      "lccChangeRate": -0.86,
      "dhwContext": 4.04,
      "predictedNextChange": -1.0585788901734219,
      "predictionLower": -17.312964366277185,
      "predictionUpper": 12.60343806915642,
      "tier": "Monitor",
      "sourceConfidence": "PDF geometry only - not cross-checked",
      "evidence": "NOAA thermal stress observed",
      "nextStep": "Coordinate bleaching survey; do not attribute thermal loss to visitors"
    },
    {
      "rank": 34,
      "island": "Mataking",
      "state": "Sabah",
      "ecoregion": "North Borneo",
      "lat": 4.58,
      "lng": 118.95,
      "marinePark": "Non-Park Reef (Semporna)",
      "surveyYear": 2025,
      "lcc": 28.75,
      "lccChangeRate": 1.86,
      "dhwContext": 4.04,
      "predictedNextChange": -1.029080790321467,
      "predictionLower": -17.28346626642523,
      "predictionUpper": 12.632936169008374,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "NOAA thermal stress observed",
      "nextStep": "Coordinate bleaching survey; do not attribute thermal loss to visitors"
    },
    {
      "rank": 35,
      "island": "Lang Tengah",
      "state": "Terengganu",
      "ecoregion": "Sunda Shelf",
      "lat": 5.7917,
      "lng": 102.8917,
      "marinePark": "Terengganu Marine Park",
      "surveyYear": 2025,
      "lcc": 26.72,
      "lccChangeRate": -9.99,
      "dhwContext": 2.05,
      "predictedNextChange": -0.7782789516603302,
      "predictionLower": -17.032664427764093,
      "predictionUpper": 12.883738007669512,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Anchor impact mentioned in Reef Check report",
      "nextStep": "Inspect mooring availability and anchoring controls"
    },
    {
      "rank": 36,
      "island": "Mantanani",
      "state": "Sabah",
      "ecoregion": "North Borneo",
      "lat": 6.7167,
      "lng": 116.35,
      "marinePark": "Mantanani Islands",
      "surveyYear": 2025,
      "lcc": 22.55,
      "lccChangeRate": -10.29,
      "dhwContext": 4.04,
      "predictedNextChange": -0.14582637801605128,
      "predictionLower": -16.400211854119814,
      "predictionUpper": 13.51619058131379,
      "tier": "Monitor",
      "sourceConfidence": "PDF geometry only - not cross-checked",
      "evidence": "NOAA thermal stress observed",
      "nextStep": "Coordinate bleaching survey; do not attribute thermal loss to visitors"
    },
    {
      "rank": 37,
      "island": "Bidong & Yu",
      "state": "Terengganu",
      "ecoregion": "Sunda Shelf",
      "lat": 5.6167,
      "lng": 103.05,
      "marinePark": "Terengganu Marine Park",
      "surveyYear": 2025,
      "lcc": 48.02,
      "lccChangeRate": -11.25,
      "dhwContext": 2.05,
      "predictedNextChange": 0.5914051583112688,
      "predictionLower": -15.662980317792496,
      "predictionUpper": 14.25342211764111,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "Waste or pollution indicator is elevated",
      "nextStep": "Inspect waste and wastewater controls"
    },
    {
      "rank": 38,
      "island": "Kapalai",
      "state": "Sabah",
      "ecoregion": "North Borneo",
      "lat": 4.225,
      "lng": 118.6833,
      "marinePark": "Non-Park Reef (Semporna)",
      "surveyYear": 2025,
      "lcc": 14.69,
      "lccChangeRate": -5.81,
      "dhwContext": 4.04,
      "predictedNextChange": 0.7700912926492062,
      "predictionLower": -15.484294183454557,
      "predictionUpper": 14.432108251979049,
      "tier": "Monitor",
      "sourceConfidence": "PDF geometry only - not cross-checked",
      "evidence": "NOAA thermal stress observed",
      "nextStep": "Coordinate bleaching survey; do not attribute thermal loss to visitors"
    },
    {
      "rank": 39,
      "island": "Mabul",
      "state": "Sabah",
      "ecoregion": "North Borneo",
      "lat": 4.2464,
      "lng": 118.6294,
      "marinePark": "Non-Park Reef (Semporna)",
      "surveyYear": 2025,
      "lcc": 26.56,
      "lccChangeRate": 4.27,
      "dhwContext": 4.04,
      "predictedNextChange": 1.1751986249231563,
      "predictionLower": -15.079186851180607,
      "predictionUpper": 14.837215584252998,
      "tier": "Monitor",
      "sourceConfidence": "mixed - markdown primary, PDF filled gaps",
      "evidence": "NOAA thermal stress observed",
      "nextStep": "Coordinate bleaching survey; do not attribute thermal loss to visitors"
    },
    {
      "rank": 40,
      "island": "Malacca",
      "state": "Malacca",
      "ecoregion": "Malacca Strait",
      "lat": 2.05,
      "lng": 102.3333,
      "marinePark": "Pulau Besar / Pulau Undan Marine Park",
      "surveyYear": 2025,
      "lcc": 32.12,
      "lccChangeRate": -1.04,
      "dhwContext": 2.05,
      "predictedNextChange": 3.483540430919274,
      "predictionLower": -12.77084504518449,
      "predictionUpper": 17.145557390249117,
      "tier": "Monitor",
      "sourceConfidence": "PDF geometry only - not cross-checked",
      "evidence": "Anchor impact mentioned in Reef Check report",
      "nextStep": "Inspect mooring availability and anchoring controls"
    }
  ],
  "islandHistory": {
    "Tioman": [
      {
        "year": 2012,
        "lcc": 55.81,
        "dhwContext": 0.15
      },
      {
        "year": 2013,
        "lcc": 55.81,
        "dhwContext": 1.32
      },
      {
        "year": 2014,
        "lcc": 60.4,
        "dhwContext": 1.47
      },
      {
        "year": 2015,
        "lcc": 61.39,
        "dhwContext": 0.0
      },
      {
        "year": 2016,
        "lcc": 59.48,
        "dhwContext": 7.25
      },
      {
        "year": 2017,
        "lcc": 66.37,
        "dhwContext": 0.0
      },
      {
        "year": 2018,
        "lcc": 62.6,
        "dhwContext": 0.15
      },
      {
        "year": 2019,
        "lcc": 63.82,
        "dhwContext": 0.3
      },
      {
        "year": 2020,
        "lcc": 63.67,
        "dhwContext": 0.91
      },
      {
        "year": 2021,
        "lcc": 60.59,
        "dhwContext": 0.16
      },
      {
        "year": 2022,
        "lcc": 63.37,
        "dhwContext": 0.33
      },
      {
        "year": 2023,
        "lcc": 64.62,
        "dhwContext": 1.2
      },
      {
        "year": 2024,
        "lcc": 58.29,
        "dhwContext": 9.44
      },
      {
        "year": 2025,
        "lcc": 42.99,
        "dhwContext": 1.88
      }
    ],
    "Kapas": [
      {
        "year": 2012,
        "lcc": 58.43,
        "dhwContext": 0.33
      },
      {
        "year": 2013,
        "lcc": 58.43,
        "dhwContext": 2.73
      },
      {
        "year": 2014,
        "lcc": 56.88,
        "dhwContext": 5.79
      },
      {
        "year": 2015,
        "lcc": 53.63,
        "dhwContext": 4.48
      },
      {
        "year": 2016,
        "lcc": 50.13,
        "dhwContext": 8.15
      },
      {
        "year": 2017,
        "lcc": 50.01,
        "dhwContext": 1.61
      },
      {
        "year": 2018,
        "lcc": 44.88,
        "dhwContext": 2.56
      },
      {
        "year": 2019,
        "lcc": 47.38,
        "dhwContext": 6.17
      },
      {
        "year": 2020,
        "lcc": 44.5,
        "dhwContext": 5.33
      },
      {
        "year": 2021,
        "lcc": 43.39,
        "dhwContext": 1.58
      },
      {
        "year": 2022,
        "lcc": 47.63,
        "dhwContext": 1.13
      },
      {
        "year": 2023,
        "lcc": 50.25,
        "dhwContext": 3.3
      },
      {
        "year": 2024,
        "lcc": 47.52,
        "dhwContext": 15.12
      },
      {
        "year": 2025,
        "lcc": 52.63,
        "dhwContext": 2.05
      }
    ],
    "Babi Tengah": [
      {
        "year": 2013,
        "lcc": 63.7,
        "dhwContext": 1.32
      }
    ],
    "Pemanggil": [
      {
        "year": 2013,
        "lcc": 48.78,
        "dhwContext": 1.32
      },
      {
        "year": 2014,
        "lcc": 54.07,
        "dhwContext": 1.47
      },
      {
        "year": 2015,
        "lcc": 55.47,
        "dhwContext": 0.0
      },
      {
        "year": 2016,
        "lcc": 48.44,
        "dhwContext": 7.25
      },
      {
        "year": 2017,
        "lcc": 51.4,
        "dhwContext": 0.0
      },
      {
        "year": 2018,
        "lcc": 55.79,
        "dhwContext": 0.15
      },
      {
        "year": 2019,
        "lcc": 52.03,
        "dhwContext": 0.3
      },
      {
        "year": 2020,
        "lcc": 49.85,
        "dhwContext": 0.91
      },
      {
        "year": 2021,
        "lcc": 43.91,
        "dhwContext": 0.16
      },
      {
        "year": 2022,
        "lcc": 48.91,
        "dhwContext": 0.33
      },
      {
        "year": 2023,
        "lcc": 46.25,
        "dhwContext": 1.2
      },
      {
        "year": 2024,
        "lcc": 47.5,
        "dhwContext": 9.44
      },
      {
        "year": 2025,
        "lcc": 43.75,
        "dhwContext": 1.88
      }
    ],
    "Sibu & Tinggi": [
      {
        "year": 2013,
        "lcc": 55.84,
        "dhwContext": 1.32
      }
    ],
    "Sembilan": [
      {
        "year": 2013,
        "lcc": 44.61,
        "dhwContext": 2.69
      },
      {
        "year": 2014,
        "lcc": 33.91,
        "dhwContext": 1.2
      },
      {
        "year": 2015,
        "lcc": 31.81,
        "dhwContext": 0.63
      },
      {
        "year": 2016,
        "lcc": 31.18,
        "dhwContext": 11.34
      },
      {
        "year": 2017,
        "lcc": 23.54,
        "dhwContext": 0.15
      },
      {
        "year": 2018,
        "lcc": 25.49,
        "dhwContext": 0.32
      },
      {
        "year": 2019,
        "lcc": 26.87,
        "dhwContext": 3.45
      },
      {
        "year": 2020,
        "lcc": 28.33,
        "dhwContext": 3.42
      },
      {
        "year": 2022,
        "lcc": 29.31,
        "dhwContext": 0.15
      },
      {
        "year": 2023,
        "lcc": 28.96,
        "dhwContext": 3.26
      },
      {
        "year": 2024,
        "lcc": 27.99,
        "dhwContext": 13.64
      }
    ],
    "Kota Belud": [
      {
        "year": 2013,
        "lcc": 17.41,
        "dhwContext": 1.88
      }
    ],
    "Labuan": [
      {
        "year": 2013,
        "lcc": 56.23,
        "dhwContext": 1.88
      },
      {
        "year": 2016,
        "lcc": 41.67,
        "dhwContext": 10.52
      },
      {
        "year": 2018,
        "lcc": 23.44,
        "dhwContext": 1.71
      },
      {
        "year": 2019,
        "lcc": 29.54,
        "dhwContext": 7.74
      },
      {
        "year": 2022,
        "lcc": 42.19,
        "dhwContext": 0.92
      },
      {
        "year": 2023,
        "lcc": 38.92,
        "dhwContext": 8.7
      },
      {
        "year": 2025,
        "lcc": 24.23,
        "dhwContext": 4.04
      }
    ],
    "Lahad Datu": [
      {
        "year": 2013,
        "lcc": 40.87,
        "dhwContext": 1.88
      },
      {
        "year": 2014,
        "lcc": 41.58,
        "dhwContext": 5.17
      },
      {
        "year": 2015,
        "lcc": 32.88,
        "dhwContext": 3.68
      },
      {
        "year": 2016,
        "lcc": 20.5,
        "dhwContext": 10.52
      },
      {
        "year": 2017,
        "lcc": 31.0,
        "dhwContext": 6.7
      },
      {
        "year": 2018,
        "lcc": 24.66,
        "dhwContext": 1.71
      },
      {
        "year": 2019,
        "lcc": 25.25,
        "dhwContext": 7.74
      },
      {
        "year": 2020,
        "lcc": 29.12,
        "dhwContext": 7.87
      },
      {
        "year": 2021,
        "lcc": 32.66,
        "dhwContext": 2.18
      },
      {
        "year": 2022,
        "lcc": 43.0,
        "dhwContext": 0.92
      },
      {
        "year": 2023,
        "lcc": 35.25,
        "dhwContext": 8.7
      },
      {
        "year": 2024,
        "lcc": 35.69,
        "dhwContext": 11.4
      },
      {
        "year": 2025,
        "lcc": 41.42,
        "dhwContext": 4.04
      }
    ],
    "Lankayan": [
      {
        "year": 2013,
        "lcc": 54.04,
        "dhwContext": 1.88
      },
      {
        "year": 2014,
        "lcc": 46.29,
        "dhwContext": 5.17
      },
      {
        "year": 2015,
        "lcc": 48.21,
        "dhwContext": 3.68
      },
      {
        "year": 2016,
        "lcc": 48.91,
        "dhwContext": 10.52
      },
      {
        "year": 2017,
        "lcc": 37.08,
        "dhwContext": 6.7
      },
      {
        "year": 2018,
        "lcc": 43.67,
        "dhwContext": 1.71
      },
      {
        "year": 2019,
        "lcc": 35.88,
        "dhwContext": 7.74
      },
      {
        "year": 2020,
        "lcc": 46.55,
        "dhwContext": 7.87
      },
      {
        "year": 2021,
        "lcc": 39.15,
        "dhwContext": 2.18
      },
      {
        "year": 2022,
        "lcc": 54.92,
        "dhwContext": 0.92
      },
      {
        "year": 2023,
        "lcc": 47.58,
        "dhwContext": 8.7
      },
      {
        "year": 2024,
        "lcc": 49.53,
        "dhwContext": 11.4
      },
      {
        "year": 2025,
        "lcc": 51.04,
        "dhwContext": 4.04
      }
    ],
    "Mantanani": [
      {
        "year": 2013,
        "lcc": 40.63,
        "dhwContext": 1.88
      },
      {
        "year": 2014,
        "lcc": 43.3,
        "dhwContext": 5.17
      },
      {
        "year": 2015,
        "lcc": 41.88,
        "dhwContext": 3.68
      },
      {
        "year": 2016,
        "lcc": 32.04,
        "dhwContext": 10.52
      },
      {
        "year": 2017,
        "lcc": 40.21,
        "dhwContext": 6.7
      },
      {
        "year": 2018,
        "lcc": 30.83,
        "dhwContext": 1.71
      },
      {
        "year": 2019,
        "lcc": 38.9,
        "dhwContext": 7.74
      },
      {
        "year": 2020,
        "lcc": 34.43,
        "dhwContext": 7.87
      },
      {
        "year": 2021,
        "lcc": 37.81,
        "dhwContext": 2.18
      },
      {
        "year": 2022,
        "lcc": 51.93,
        "dhwContext": 0.92
      },
      {
        "year": 2023,
        "lcc": 30.94,
        "dhwContext": 8.7
      },
      {
        "year": 2024,
        "lcc": 32.84,
        "dhwContext": 11.4
      },
      {
        "year": 2025,
        "lcc": 22.55,
        "dhwContext": 4.04
      }
    ],
    "Mataking": [
      {
        "year": 2013,
        "lcc": 36.29,
        "dhwContext": 1.88
      },
      {
        "year": 2015,
        "lcc": 33.64,
        "dhwContext": 3.68
      },
      {
        "year": 2016,
        "lcc": 35.52,
        "dhwContext": 10.52
      },
      {
        "year": 2017,
        "lcc": 27.29,
        "dhwContext": 6.7
      },
      {
        "year": 2018,
        "lcc": 23.03,
        "dhwContext": 1.71
      },
      {
        "year": 2019,
        "lcc": 33.23,
        "dhwContext": 7.74
      },
      {
        "year": 2021,
        "lcc": 21.37,
        "dhwContext": 2.18
      },
      {
        "year": 2022,
        "lcc": 36.04,
        "dhwContext": 0.92
      },
      {
        "year": 2023,
        "lcc": 36.58,
        "dhwContext": 8.7
      },
      {
        "year": 2024,
        "lcc": 26.89,
        "dhwContext": 11.4
      },
      {
        "year": 2025,
        "lcc": 28.75,
        "dhwContext": 4.04
      }
    ],
    "Semporna": [
      {
        "year": 2013,
        "lcc": 25.98,
        "dhwContext": 1.88
      },
      {
        "year": 2014,
        "lcc": 39.94,
        "dhwContext": 5.17
      },
      {
        "year": 2015,
        "lcc": 31.29,
        "dhwContext": 3.68
      }
    ],
    "Tun Sakaran Marine Park": [
      {
        "year": 2013,
        "lcc": 43.2,
        "dhwContext": 1.88
      },
      {
        "year": 2014,
        "lcc": 50.4,
        "dhwContext": 5.17
      },
      {
        "year": 2015,
        "lcc": 54.11,
        "dhwContext": 3.68
      },
      {
        "year": 2016,
        "lcc": 47.59,
        "dhwContext": 10.52
      },
      {
        "year": 2017,
        "lcc": 50.67,
        "dhwContext": 6.7
      },
      {
        "year": 2018,
        "lcc": 54.38,
        "dhwContext": 1.71
      },
      {
        "year": 2020,
        "lcc": 33.33,
        "dhwContext": 7.87
      },
      {
        "year": 2021,
        "lcc": 36.05,
        "dhwContext": 2.18
      },
      {
        "year": 2022,
        "lcc": 51.56,
        "dhwContext": 0.92
      },
      {
        "year": 2023,
        "lcc": 45.83,
        "dhwContext": 8.7
      },
      {
        "year": 2024,
        "lcc": 55.78,
        "dhwContext": 11.4
      },
      {
        "year": 2025,
        "lcc": 51.77,
        "dhwContext": 4.04
      }
    ],
    "Tunku Abdul Rahman Park": [
      {
        "year": 2013,
        "lcc": 40.0,
        "dhwContext": 1.88
      },
      {
        "year": 2014,
        "lcc": 38.46,
        "dhwContext": 5.17
      },
      {
        "year": 2015,
        "lcc": 32.7,
        "dhwContext": 3.68
      },
      {
        "year": 2016,
        "lcc": 50.24,
        "dhwContext": 10.52
      },
      {
        "year": 2017,
        "lcc": 37.81,
        "dhwContext": 6.7
      },
      {
        "year": 2020,
        "lcc": 46.71,
        "dhwContext": 7.87
      },
      {
        "year": 2021,
        "lcc": 48.35,
        "dhwContext": 2.18
      },
      {
        "year": 2022,
        "lcc": 20.07,
        "dhwContext": 0.92
      },
      {
        "year": 2023,
        "lcc": 21.09,
        "dhwContext": 8.7
      },
      {
        "year": 2024,
        "lcc": 13.98,
        "dhwContext": 11.4
      },
      {
        "year": 2025,
        "lcc": 13.12,
        "dhwContext": 4.04
      }
    ],
    "Kuching": [
      {
        "year": 2013,
        "lcc": 75.7,
        "dhwContext": 1.85
      },
      {
        "year": 2014,
        "lcc": 55.0,
        "dhwContext": 1.24
      },
      {
        "year": 2015,
        "lcc": 69.69,
        "dhwContext": 1.19
      }
    ],
    "Miri": [
      {
        "year": 2013,
        "lcc": 53.1,
        "dhwContext": 1.85
      },
      {
        "year": 2014,
        "lcc": 52.08,
        "dhwContext": 1.24
      },
      {
        "year": 2015,
        "lcc": 45.73,
        "dhwContext": 1.19
      },
      {
        "year": 2016,
        "lcc": 43.65,
        "dhwContext": 1.79
      },
      {
        "year": 2017,
        "lcc": 54.9,
        "dhwContext": 1.97
      },
      {
        "year": 2018,
        "lcc": 46.98,
        "dhwContext": 1.27
      },
      {
        "year": 2019,
        "lcc": 50.93,
        "dhwContext": 0.0
      },
      {
        "year": 2022,
        "lcc": 48.59,
        "dhwContext": 0.59
      },
      {
        "year": 2023,
        "lcc": 45.16,
        "dhwContext": 2.62
      }
    ],
    "Bidong & Yu": [
      {
        "year": 2013,
        "lcc": 54.53,
        "dhwContext": 2.73
      },
      {
        "year": 2014,
        "lcc": 54.58,
        "dhwContext": 5.79
      },
      {
        "year": 2015,
        "lcc": 62.5,
        "dhwContext": 4.48
      },
      {
        "year": 2016,
        "lcc": 53.34,
        "dhwContext": 8.15
      },
      {
        "year": 2017,
        "lcc": 48.33,
        "dhwContext": 1.61
      },
      {
        "year": 2018,
        "lcc": 51.98,
        "dhwContext": 2.56
      },
      {
        "year": 2019,
        "lcc": 44.59,
        "dhwContext": 6.17
      },
      {
        "year": 2020,
        "lcc": 46.65,
        "dhwContext": 5.33
      },
      {
        "year": 2021,
        "lcc": 55.52,
        "dhwContext": 1.58
      },
      {
        "year": 2022,
        "lcc": 63.54,
        "dhwContext": 1.13
      },
      {
        "year": 2023,
        "lcc": 67.61,
        "dhwContext": 3.3
      },
      {
        "year": 2024,
        "lcc": 59.27,
        "dhwContext": 15.12
      },
      {
        "year": 2025,
        "lcc": 48.02,
        "dhwContext": 2.05
      }
    ],
    "Perhentian": [
      {
        "year": 2013,
        "lcc": 56.63,
        "dhwContext": 2.73
      },
      {
        "year": 2014,
        "lcc": 53.62,
        "dhwContext": 5.79
      },
      {
        "year": 2015,
        "lcc": 50.12,
        "dhwContext": 4.48
      },
      {
        "year": 2016,
        "lcc": 51.75,
        "dhwContext": 8.15
      },
      {
        "year": 2017,
        "lcc": 42.32,
        "dhwContext": 1.61
      },
      {
        "year": 2018,
        "lcc": 43.69,
        "dhwContext": 2.56
      },
      {
        "year": 2019,
        "lcc": 35.5,
        "dhwContext": 6.17
      },
      {
        "year": 2020,
        "lcc": 38.11,
        "dhwContext": 5.33
      },
      {
        "year": 2021,
        "lcc": 42.43,
        "dhwContext": 1.58
      },
      {
        "year": 2022,
        "lcc": 41.31,
        "dhwContext": 1.13
      },
      {
        "year": 2023,
        "lcc": 40.25,
        "dhwContext": 3.3
      },
      {
        "year": 2024,
        "lcc": 39.19,
        "dhwContext": 15.12
      },
      {
        "year": 2025,
        "lcc": 32.44,
        "dhwContext": 2.05
      }
    ],
    "Redang": [
      {
        "year": 2013,
        "lcc": 54.83,
        "dhwContext": 2.73
      },
      {
        "year": 2014,
        "lcc": 58.13,
        "dhwContext": 5.79
      },
      {
        "year": 2015,
        "lcc": 64.12,
        "dhwContext": 4.48
      },
      {
        "year": 2016,
        "lcc": 55.41,
        "dhwContext": 8.15
      },
      {
        "year": 2017,
        "lcc": 49.95,
        "dhwContext": 1.61
      },
      {
        "year": 2018,
        "lcc": 44.22,
        "dhwContext": 2.56
      },
      {
        "year": 2019,
        "lcc": 28.49,
        "dhwContext": 6.17
      },
      {
        "year": 2020,
        "lcc": 35.46,
        "dhwContext": 5.33
      },
      {
        "year": 2021,
        "lcc": 55.82,
        "dhwContext": 1.58
      },
      {
        "year": 2022,
        "lcc": 48.28,
        "dhwContext": 1.13
      },
      {
        "year": 2023,
        "lcc": 34.31,
        "dhwContext": 3.3
      },
      {
        "year": 2024,
        "lcc": 29.17,
        "dhwContext": 15.12
      },
      {
        "year": 2025,
        "lcc": 25.89,
        "dhwContext": 2.05
      }
    ],
    "Tenggol": [
      {
        "year": 2013,
        "lcc": 56.2,
        "dhwContext": 2.73
      },
      {
        "year": 2014,
        "lcc": 53.54,
        "dhwContext": 5.79
      },
      {
        "year": 2015,
        "lcc": 58.65,
        "dhwContext": 4.48
      },
      {
        "year": 2016,
        "lcc": 60.31,
        "dhwContext": 8.15
      },
      {
        "year": 2017,
        "lcc": 52.92,
        "dhwContext": 1.61
      },
      {
        "year": 2018,
        "lcc": 51.77,
        "dhwContext": 2.56
      },
      {
        "year": 2019,
        "lcc": 47.19,
        "dhwContext": 6.17
      },
      {
        "year": 2020,
        "lcc": 52.4,
        "dhwContext": 5.33
      },
      {
        "year": 2021,
        "lcc": 57.8,
        "dhwContext": 1.58
      },
      {
        "year": 2022,
        "lcc": 51.44,
        "dhwContext": 1.13
      },
      {
        "year": 2023,
        "lcc": 46.67,
        "dhwContext": 3.3
      },
      {
        "year": 2024,
        "lcc": 57.08,
        "dhwContext": 15.12
      },
      {
        "year": 2025,
        "lcc": 54.17,
        "dhwContext": 2.05
      }
    ],
    "Sibu": [
      {
        "year": 2014,
        "lcc": 46.66,
        "dhwContext": 1.47
      },
      {
        "year": 2015,
        "lcc": 51.36,
        "dhwContext": 0.0
      },
      {
        "year": 2016,
        "lcc": 63.75,
        "dhwContext": 7.25
      },
      {
        "year": 2017,
        "lcc": 58.86,
        "dhwContext": 0.0
      },
      {
        "year": 2018,
        "lcc": 56.88,
        "dhwContext": 0.15
      },
      {
        "year": 2019,
        "lcc": 55.84,
        "dhwContext": 0.3
      },
      {
        "year": 2020,
        "lcc": 59.37,
        "dhwContext": 0.91
      },
      {
        "year": 2021,
        "lcc": 45.93,
        "dhwContext": 0.16
      },
      {
        "year": 2022,
        "lcc": 53.85,
        "dhwContext": 0.33
      },
      {
        "year": 2023,
        "lcc": 57.6,
        "dhwContext": 1.2
      },
      {
        "year": 2024,
        "lcc": 50.73,
        "dhwContext": 9.44
      },
      {
        "year": 2025,
        "lcc": 52.81,
        "dhwContext": 1.88
      }
    ],
    "Tinggi": [
      {
        "year": 2014,
        "lcc": 61.88,
        "dhwContext": 1.47
      },
      {
        "year": 2015,
        "lcc": 70.0,
        "dhwContext": 0.0
      },
      {
        "year": 2016,
        "lcc": 64.22,
        "dhwContext": 7.25
      },
      {
        "year": 2017,
        "lcc": 64.53,
        "dhwContext": 0.0
      },
      {
        "year": 2018,
        "lcc": 60.63,
        "dhwContext": 0.15
      },
      {
        "year": 2019,
        "lcc": 58.59,
        "dhwContext": 0.3
      },
      {
        "year": 2020,
        "lcc": 45.16,
        "dhwContext": 0.91
      },
      {
        "year": 2021,
        "lcc": 48.13,
        "dhwContext": 0.16
      },
      {
        "year": 2022,
        "lcc": 48.28,
        "dhwContext": 0.33
      },
      {
        "year": 2023,
        "lcc": 50.0,
        "dhwContext": 1.2
      },
      {
        "year": 2024,
        "lcc": 56.72,
        "dhwContext": 9.44
      },
      {
        "year": 2025,
        "lcc": 52.5,
        "dhwContext": 1.88
      }
    ],
    "Pangkor Laut": [
      {
        "year": 2014,
        "lcc": 55.63,
        "dhwContext": 1.2
      },
      {
        "year": 2015,
        "lcc": 68.75,
        "dhwContext": 0.63
      },
      {
        "year": 2016,
        "lcc": 88.75,
        "dhwContext": 11.34
      },
      {
        "year": 2017,
        "lcc": 66.25,
        "dhwContext": 0.15
      },
      {
        "year": 2018,
        "lcc": 28.75,
        "dhwContext": 0.32
      },
      {
        "year": 2019,
        "lcc": 53.75,
        "dhwContext": 3.45
      },
      {
        "year": 2020,
        "lcc": 60.62,
        "dhwContext": 3.42
      },
      {
        "year": 2022,
        "lcc": 61.26,
        "dhwContext": 0.15
      },
      {
        "year": 2023,
        "lcc": 53.75,
        "dhwContext": 3.26
      },
      {
        "year": 2024,
        "lcc": 51.89,
        "dhwContext": 13.64
      }
    ],
    "Mataking & Pom Pom": [
      {
        "year": 2014,
        "lcc": 27.04,
        "dhwContext": 5.17
      }
    ],
    "Sipadan": [
      {
        "year": 2014,
        "lcc": 60.4,
        "dhwContext": 5.17
      },
      {
        "year": 2015,
        "lcc": 53.33,
        "dhwContext": 3.68
      },
      {
        "year": 2016,
        "lcc": 43.49,
        "dhwContext": 10.52
      },
      {
        "year": 2017,
        "lcc": 49.95,
        "dhwContext": 6.7
      },
      {
        "year": 2018,
        "lcc": 43.49,
        "dhwContext": 1.71
      },
      {
        "year": 2020,
        "lcc": 40.06,
        "dhwContext": 7.87
      },
      {
        "year": 2021,
        "lcc": 54.48,
        "dhwContext": 2.18
      },
      {
        "year": 2022,
        "lcc": 50.57,
        "dhwContext": 0.92
      },
      {
        "year": 2023,
        "lcc": 56.88,
        "dhwContext": 8.7
      },
      {
        "year": 2024,
        "lcc": 63.29,
        "dhwContext": 11.4
      },
      {
        "year": 2025,
        "lcc": 55.21,
        "dhwContext": 4.04
      }
    ],
    "Usukan Cove": [
      {
        "year": 2014,
        "lcc": 38.44,
        "dhwContext": 5.17
      },
      {
        "year": 2015,
        "lcc": 35.63,
        "dhwContext": 3.68
      },
      {
        "year": 2016,
        "lcc": 33.02,
        "dhwContext": 10.52
      },
      {
        "year": 2017,
        "lcc": 25.84,
        "dhwContext": 6.7
      },
      {
        "year": 2018,
        "lcc": 34.17,
        "dhwContext": 1.71
      },
      {
        "year": 2019,
        "lcc": 53.02,
        "dhwContext": 7.74
      },
      {
        "year": 2020,
        "lcc": 34.99,
        "dhwContext": 7.87
      },
      {
        "year": 2021,
        "lcc": 35.83,
        "dhwContext": 2.18
      },
      {
        "year": 2022,
        "lcc": 29.9,
        "dhwContext": 0.92
      },
      {
        "year": 2023,
        "lcc": 25.73,
        "dhwContext": 8.7
      },
      {
        "year": 2024,
        "lcc": 32.44,
        "dhwContext": 11.4
      },
      {
        "year": 2025,
        "lcc": 15.94,
        "dhwContext": 4.04
      }
    ],
    "Payar": [
      {
        "year": 2015,
        "lcc": 40.42,
        "dhwContext": 0.63
      },
      {
        "year": 2016,
        "lcc": 44.38,
        "dhwContext": 11.34
      },
      {
        "year": 2017,
        "lcc": 51.38,
        "dhwContext": 0.15
      },
      {
        "year": 2018,
        "lcc": 53.38,
        "dhwContext": 0.32
      },
      {
        "year": 2019,
        "lcc": 50.88,
        "dhwContext": 3.45
      },
      {
        "year": 2020,
        "lcc": 60.48,
        "dhwContext": 3.42
      },
      {
        "year": 2021,
        "lcc": 44.88,
        "dhwContext": 1.56
      },
      {
        "year": 2022,
        "lcc": 57.13,
        "dhwContext": 0.15
      },
      {
        "year": 2023,
        "lcc": 64.0,
        "dhwContext": 3.26
      },
      {
        "year": 2024,
        "lcc": 49.13,
        "dhwContext": 13.64
      },
      {
        "year": 2025,
        "lcc": 42.29,
        "dhwContext": 1.94
      }
    ],
    "Balambangan": [
      {
        "year": 2015,
        "lcc": 72.29,
        "dhwContext": 3.68
      }
    ],
    "Berungus": [
      {
        "year": 2015,
        "lcc": 54.22,
        "dhwContext": 3.68
      }
    ],
    "Kapalai": [
      {
        "year": 2015,
        "lcc": 7.63,
        "dhwContext": 3.68
      },
      {
        "year": 2016,
        "lcc": 11.26,
        "dhwContext": 10.52
      },
      {
        "year": 2017,
        "lcc": 12.81,
        "dhwContext": 6.7
      },
      {
        "year": 2018,
        "lcc": 18.44,
        "dhwContext": 1.71
      },
      {
        "year": 2019,
        "lcc": 14.68,
        "dhwContext": 7.74
      },
      {
        "year": 2020,
        "lcc": 17.19,
        "dhwContext": 7.87
      },
      {
        "year": 2021,
        "lcc": 18.23,
        "dhwContext": 2.18
      },
      {
        "year": 2022,
        "lcc": 24.27,
        "dhwContext": 0.92
      },
      {
        "year": 2023,
        "lcc": 21.15,
        "dhwContext": 8.7
      },
      {
        "year": 2024,
        "lcc": 20.5,
        "dhwContext": 11.4
      },
      {
        "year": 2025,
        "lcc": 14.69,
        "dhwContext": 4.04
      }
    ],
    "Mabul": [
      {
        "year": 2015,
        "lcc": 20.13,
        "dhwContext": 3.68
      },
      {
        "year": 2016,
        "lcc": 27.61,
        "dhwContext": 10.52
      },
      {
        "year": 2017,
        "lcc": 30.41,
        "dhwContext": 6.7
      },
      {
        "year": 2018,
        "lcc": 34.51,
        "dhwContext": 1.71
      },
      {
        "year": 2019,
        "lcc": 27.71,
        "dhwContext": 7.74
      },
      {
        "year": 2020,
        "lcc": 21.87,
        "dhwContext": 7.87
      },
      {
        "year": 2021,
        "lcc": 27.8,
        "dhwContext": 2.18
      },
      {
        "year": 2022,
        "lcc": 33.23,
        "dhwContext": 0.92
      },
      {
        "year": 2023,
        "lcc": 23.01,
        "dhwContext": 8.7
      },
      {
        "year": 2024,
        "lcc": 22.29,
        "dhwContext": 11.4
      },
      {
        "year": 2025,
        "lcc": 26.56,
        "dhwContext": 4.04
      }
    ],
    "Maliangin": [
      {
        "year": 2015,
        "lcc": 46.68,
        "dhwContext": 3.68
      }
    ],
    "Penyu": [
      {
        "year": 2015,
        "lcc": 41.46,
        "dhwContext": 3.68
      },
      {
        "year": 2016,
        "lcc": 31.67,
        "dhwContext": 10.52
      },
      {
        "year": 2017,
        "lcc": 42.85,
        "dhwContext": 6.7
      },
      {
        "year": 2018,
        "lcc": 45.76,
        "dhwContext": 1.71
      },
      {
        "year": 2020,
        "lcc": 44.44,
        "dhwContext": 7.87
      },
      {
        "year": 2021,
        "lcc": 46.69,
        "dhwContext": 2.18
      },
      {
        "year": 2022,
        "lcc": 42.92,
        "dhwContext": 0.92
      },
      {
        "year": 2023,
        "lcc": 32.42,
        "dhwContext": 8.7
      },
      {
        "year": 2024,
        "lcc": 39.3,
        "dhwContext": 11.4
      },
      {
        "year": 2025,
        "lcc": 37.77,
        "dhwContext": 4.04
      }
    ],
    "Tiga": [
      {
        "year": 2015,
        "lcc": 29.58,
        "dhwContext": 3.68
      },
      {
        "year": 2016,
        "lcc": 43.43,
        "dhwContext": 10.52
      },
      {
        "year": 2017,
        "lcc": 35.63,
        "dhwContext": 6.7
      },
      {
        "year": 2020,
        "lcc": 28.92,
        "dhwContext": 7.87
      },
      {
        "year": 2021,
        "lcc": 43.58,
        "dhwContext": 2.18
      },
      {
        "year": 2022,
        "lcc": 33.39,
        "dhwContext": 0.92
      },
      {
        "year": 2023,
        "lcc": 33.39,
        "dhwContext": 8.7
      },
      {
        "year": 2024,
        "lcc": 22.67,
        "dhwContext": 11.4
      },
      {
        "year": 2025,
        "lcc": 21.52,
        "dhwContext": 4.04
      }
    ],
    "Pom Pom": [
      {
        "year": 2016,
        "lcc": 18.76,
        "dhwContext": 10.52
      },
      {
        "year": 2018,
        "lcc": 12.01,
        "dhwContext": 1.71
      },
      {
        "year": 2019,
        "lcc": 22.77,
        "dhwContext": 7.74
      }
    ],
    "Rawa": [
      {
        "year": 2017,
        "lcc": 43.75,
        "dhwContext": 0.0
      },
      {
        "year": 2018,
        "lcc": 60.63,
        "dhwContext": 0.15
      },
      {
        "year": 2019,
        "lcc": 74.63,
        "dhwContext": 0.3
      },
      {
        "year": 2022,
        "lcc": 62.35,
        "dhwContext": 0.33
      },
      {
        "year": 2023,
        "lcc": 59.31,
        "dhwContext": 1.2
      },
      {
        "year": 2024,
        "lcc": 56.53,
        "dhwContext": 9.44
      },
      {
        "year": 2025,
        "lcc": 48.85,
        "dhwContext": 1.88
      }
    ],
    "Tengah": [
      {
        "year": 2017,
        "lcc": 46.25,
        "dhwContext": 0.0
      },
      {
        "year": 2022,
        "lcc": 53.41,
        "dhwContext": 0.33
      },
      {
        "year": 2023,
        "lcc": 48.69,
        "dhwContext": 1.2
      },
      {
        "year": 2024,
        "lcc": 47.95,
        "dhwContext": 9.44
      },
      {
        "year": 2025,
        "lcc": 45.73,
        "dhwContext": 1.88
      }
    ],
    "Northern Semporna": [
      {
        "year": 2017,
        "lcc": 28.79,
        "dhwContext": 6.7
      }
    ],
    "Southern Semporna": [
      {
        "year": 2017,
        "lcc": 33.6,
        "dhwContext": 6.7
      }
    ],
    "Aur & Dayang": [
      {
        "year": 2018,
        "lcc": 44.58,
        "dhwContext": 0.15
      },
      {
        "year": 2019,
        "lcc": 40.21,
        "dhwContext": 0.3
      },
      {
        "year": 2020,
        "lcc": 36.58,
        "dhwContext": 0.91
      },
      {
        "year": 2021,
        "lcc": 38.65,
        "dhwContext": 0.16
      },
      {
        "year": 2022,
        "lcc": 39.17,
        "dhwContext": 0.33
      },
      {
        "year": 2023,
        "lcc": 35.21,
        "dhwContext": 1.2
      },
      {
        "year": 2024,
        "lcc": 38.03,
        "dhwContext": 9.44
      },
      {
        "year": 2025,
        "lcc": 35.42,
        "dhwContext": 1.88
      }
    ],
    "Lang Tengah": [
      {
        "year": 2018,
        "lcc": 36.88,
        "dhwContext": 2.56
      },
      {
        "year": 2022,
        "lcc": 46.09,
        "dhwContext": 1.13
      },
      {
        "year": 2023,
        "lcc": 55.48,
        "dhwContext": 3.3
      },
      {
        "year": 2024,
        "lcc": 36.71,
        "dhwContext": 15.12
      },
      {
        "year": 2025,
        "lcc": 26.72,
        "dhwContext": 2.05
      }
    ],
    "Besar": [
      {
        "year": 2020,
        "lcc": 35.17,
        "dhwContext": 0.91
      },
      {
        "year": 2021,
        "lcc": 39.81,
        "dhwContext": 0.16
      },
      {
        "year": 2022,
        "lcc": 48.39,
        "dhwContext": 0.33
      },
      {
        "year": 2023,
        "lcc": 50.63,
        "dhwContext": 1.2
      },
      {
        "year": 2024,
        "lcc": 42.41,
        "dhwContext": 9.44
      },
      {
        "year": 2025,
        "lcc": 43.04,
        "dhwContext": 1.88
      }
    ],
    "Lima": [
      {
        "year": 2021,
        "lcc": 49.38,
        "dhwContext": 0.16
      },
      {
        "year": 2022,
        "lcc": 51.88,
        "dhwContext": 0.33
      },
      {
        "year": 2023,
        "lcc": 62.92,
        "dhwContext": 1.2
      },
      {
        "year": 2024,
        "lcc": 62.28,
        "dhwContext": 9.44
      },
      {
        "year": 2025,
        "lcc": 51.88,
        "dhwContext": 1.88
      }
    ],
    "Malacca": [
      {
        "year": 2021,
        "lcc": 35.61,
        "dhwContext": 1.58
      },
      {
        "year": 2022,
        "lcc": 30.12,
        "dhwContext": 1.13
      },
      {
        "year": 2023,
        "lcc": 34.61,
        "dhwContext": 3.3
      },
      {
        "year": 2024,
        "lcc": 33.16,
        "dhwContext": 15.12
      },
      {
        "year": 2025,
        "lcc": 32.12,
        "dhwContext": 2.05
      }
    ],
    "Port Dickson": [
      {
        "year": 2021,
        "lcc": 50.95,
        "dhwContext": 1.58
      },
      {
        "year": 2022,
        "lcc": 16.57,
        "dhwContext": 1.13
      },
      {
        "year": 2023,
        "lcc": 45.94,
        "dhwContext": 3.3
      },
      {
        "year": 2024,
        "lcc": 42.51,
        "dhwContext": 15.12
      },
      {
        "year": 2025,
        "lcc": 35.01,
        "dhwContext": 2.05
      }
    ],
    "Larapan": [
      {
        "year": 2021,
        "lcc": 67.08,
        "dhwContext": 2.18
      },
      {
        "year": 2022,
        "lcc": 55.63,
        "dhwContext": 0.92
      },
      {
        "year": 2023,
        "lcc": 56.38,
        "dhwContext": 8.7
      },
      {
        "year": 2024,
        "lcc": 58.5,
        "dhwContext": 11.4
      },
      {
        "year": 2025,
        "lcc": 50.88,
        "dhwContext": 4.04
      }
    ],
    "Gual": [
      {
        "year": 2022,
        "lcc": 56.94,
        "dhwContext": 0.33
      },
      {
        "year": 2023,
        "lcc": 54.24,
        "dhwContext": 1.2
      },
      {
        "year": 2024,
        "lcc": 55.76,
        "dhwContext": 9.44
      },
      {
        "year": 2025,
        "lcc": 45.31,
        "dhwContext": 1.88
      }
    ],
    "Harimau": [
      {
        "year": 2022,
        "lcc": 52.59,
        "dhwContext": 0.33
      },
      {
        "year": 2023,
        "lcc": 64.11,
        "dhwContext": 1.2
      },
      {
        "year": 2024,
        "lcc": 60.27,
        "dhwContext": 9.44
      },
      {
        "year": 2025,
        "lcc": 48.96,
        "dhwContext": 1.88
      }
    ],
    "Hujung": [
      {
        "year": 2022,
        "lcc": 53.19,
        "dhwContext": 0.33
      },
      {
        "year": 2023,
        "lcc": 55.83,
        "dhwContext": 1.2
      },
      {
        "year": 2024,
        "lcc": 46.6,
        "dhwContext": 9.44
      },
      {
        "year": 2025,
        "lcc": 41.77,
        "dhwContext": 1.88
      }
    ],
    "Mensirip": [
      {
        "year": 2022,
        "lcc": 69.2,
        "dhwContext": 0.33
      },
      {
        "year": 2023,
        "lcc": 68.12,
        "dhwContext": 1.2
      },
      {
        "year": 2024,
        "lcc": 58.83,
        "dhwContext": 9.44
      },
      {
        "year": 2025,
        "lcc": 54.17,
        "dhwContext": 1.88
      }
    ],
    "Mertang": [
      {
        "year": 2022,
        "lcc": 76.04,
        "dhwContext": 0.33
      },
      {
        "year": 2023,
        "lcc": 68.54,
        "dhwContext": 1.2
      },
      {
        "year": 2024,
        "lcc": 69.58,
        "dhwContext": 9.44
      },
      {
        "year": 2025,
        "lcc": 58.33,
        "dhwContext": 1.88
      }
    ],
    "Singa": [
      {
        "year": 2022,
        "lcc": 67.51,
        "dhwContext": 0.15
      },
      {
        "year": 2023,
        "lcc": 64.39,
        "dhwContext": 3.26
      }
    ],
    "Tun Mustapha Park": [
      {
        "year": 2022,
        "lcc": 45.59,
        "dhwContext": 0.92
      },
      {
        "year": 2023,
        "lcc": 42.19,
        "dhwContext": 8.7
      },
      {
        "year": 2024,
        "lcc": 44.83,
        "dhwContext": 11.4
      },
      {
        "year": 2025,
        "lcc": 40.35,
        "dhwContext": 4.04
      }
    ],
    "Rhu": [
      {
        "year": 2022,
        "lcc": 43.44,
        "dhwContext": 1.13
      },
      {
        "year": 2023,
        "lcc": 30.63,
        "dhwContext": 3.3
      },
      {
        "year": 2024,
        "lcc": 28.29,
        "dhwContext": 15.12
      },
      {
        "year": 2025,
        "lcc": 27.92,
        "dhwContext": 2.05
      }
    ],
    "Seri Buat": [
      {
        "year": 2023,
        "lcc": 63.73,
        "dhwContext": 3.3
      },
      {
        "year": 2024,
        "lcc": 62.06,
        "dhwContext": 15.12
      },
      {
        "year": 2025,
        "lcc": 54.22,
        "dhwContext": 2.05
      }
    ]
  },
  "factorRelationships": [
    {
      "factor": "noaa_max_dhw",
      "analysis": "Spearman rank correlation",
      "n": "348",
      "statistic": "-0.1045779727630862",
      "statistic_unit": "rho",
      "p_value": "0.051270888572376425",
      "caution": "Descriptive lagged association; not a causal effect"
    },
    {
      "factor": "noaa_mean_ssta",
      "analysis": "Spearman rank correlation",
      "n": "348",
      "statistic": "-0.06056818930566387",
      "statistic_unit": "rho",
      "p_value": "0.2598039926898717",
      "caution": "Descriptive lagged association; not a causal effect"
    },
    {
      "factor": "grp_disturbance_indicators",
      "analysis": "Spearman rank correlation",
      "n": "338",
      "statistic": "0.07772612436258132",
      "statistic_unit": "rho",
      "p_value": "0.15391408226206862",
      "caution": "Descriptive lagged association; not a causal effect"
    },
    {
      "factor": "grp_pollution_indicators",
      "analysis": "Spearman rank correlation",
      "n": "338",
      "statistic": "0.14597611401784685",
      "statistic_unit": "rho",
      "p_value": "0.00718360745525168",
      "caution": "Descriptive lagged association; not a causal effect"
    },
    {
      "factor": "fish_parrotfish",
      "analysis": "Spearman rank correlation",
      "n": "348",
      "statistic": "-0.0326674872877121",
      "statistic_unit": "rho",
      "p_value": "0.5436029873395897",
      "caution": "Descriptive lagged association; not a causal effect"
    },
    {
      "factor": "grazer_ratio",
      "analysis": "Spearman rank correlation",
      "n": "331",
      "statistic": "-0.05970715805382468",
      "statistic_unit": "rho",
      "p_value": "0.27874907864012083",
      "caution": "Descriptive lagged association; not a causal effect"
    },
    {
      "factor": "impact_anchor",
      "analysis": "Mean difference: mentioned minus not mentioned",
      "n": "348",
      "statistic": "0.7535327329651386",
      "statistic_unit": "percentage points per year",
      "p_value": "0.6580050963797206",
      "caution": "Narrative mention comparison; absence may mean unreported"
    },
    {
      "factor": "impact_trash",
      "analysis": "Mean difference: mentioned minus not mentioned",
      "n": "348",
      "statistic": "-0.3909071505171756",
      "statistic_unit": "percentage points per year",
      "p_value": "0.6040435948163754",
      "caution": "Narrative mention comparison; absence may mean unreported"
    },
    {
      "factor": "impact_bleaching",
      "analysis": "Mean difference: mentioned minus not mentioned",
      "n": "348",
      "statistic": "0.8710021173123366",
      "statistic_unit": "percentage points per year",
      "p_value": "0.5471291369752176",
      "caution": "Narrative mention comparison; absence may mean unreported"
    }
  ],
  "heatSummary": [
    {
      "heat_category": "DHW < 1",
      "n": "81",
      "median_next_change_pp_per_year": "-0.63",
      "mean_next_change_pp_per_year": "-0.5503827160493827"
    },
    {
      "heat_category": "DHW 1–<4",
      "n": "128",
      "median_next_change_pp_per_year": "-1.06",
      "mean_next_change_pp_per_year": "-0.59840625"
    },
    {
      "heat_category": "DHW ≥ 4",
      "n": "139",
      "median_next_change_pp_per_year": "-1.11",
      "mean_next_change_pp_per_year": "-1.3778992805755395"
    }
  ],
  "modelMetrics": {
    "prediction_target": "Next observed annualised live coral cover change",
    "validation": "Expanding-window evaluation on the five latest target years",
    "training_transitions": 348,
    "evaluation_observations": 183,
    "test_years": [
      2021,
      2022,
      2023,
      2024,
      2025
    ],
    "best_candidate": "Gradient boosting",
    "baseline_mae": 5.991036572720733,
    "best_mae": 5.859442920192883,
    "mae_improvement_pct": 2.1965089167881495,
    "beats_baseline": true,
    "deployment_status": "screening_only",
    "uncertainty_label": "Pooled empirical 95% forward-residual range",
    "lower_residual_quantile": -16.254385476103764,
    "upper_residual_quantile": 13.662016959329842,
    "model_comparison": {
      "Baseline mean": {
        "MAE": 5.991036572720733,
        "RMSE": 8.100134037133156,
        "R2": -0.01912875323556551
      },
      "Ridge regression": {
        "MAE": 5.989868551402971,
        "RMSE": 7.938953774203554,
        "R2": 0.02102592672483794
      },
      "Gradient boosting": {
        "MAE": 5.859442920192883,
        "RMSE": 7.738822726942544,
        "R2": 0.06976121965758453
      },
      "Random forest": {
        "MAE": 6.073604250849071,
        "RMSE": 8.016583062605548,
        "R2": 0.001786963255266727
      }
    },
    "validation_by_year": [
      {
        "target_year": 2021,
        "n": 24,
        "mae": 5.699837958186007,
        "rmse": 7.580132511639961,
        "r2": 0.10698435283396346,
        "bias": -2.4031913472193795
      },
      {
        "target_year": 2022,
        "n": 35,
        "mae": 6.943627326142161,
        "rmse": 9.95500600929782,
        "r2": 0.11671892537391992,
        "bias": -0.02610073128010702
      },
      {
        "target_year": 2023,
        "n": 43,
        "mae": 5.75575686509108,
        "rmse": 7.239246743069443,
        "r2": 0.1784066636772661,
        "bias": 0.8746988044550557
      },
      {
        "target_year": 2024,
        "n": 41,
        "mae": 5.600589599274473,
        "rmse": 7.061191062718651,
        "r2": -0.2864765388207775,
        "bias": 2.2610978641627018
      },
      {
        "target_year": 2025,
        "n": 40,
        "mae": 5.3833317053672,
        "rmse": 6.735009552131487,
        "r2": -0.653635666315163,
        "bias": 4.451967459018678
      }
    ],
    "permutation_importance": {
      "survey_year": -0.0007260397408757549,
      "live_coral_cover_pct": -0.02031872488877245,
      "lcc_change_rate": 0.1416344392504228,
      "island_vs_region_pct": 0.27836434454882836,
      "grp_available_substrate": -0.0745429138098649,
      "grp_sand": 0.026751856815825835,
      "grp_disturbance_indicators": -0.006506107900597298,
      "grp_pollution_indicators": -0.005273941601058144,
      "fish_butterflyfish": -0.0006043312329523188,
      "fish_snapper": 0.030873099763612046,
      "fish_parrotfish": 0.0564443553694937,
      "fish_grouper": 0.022735032626926097,
      "inv_diadema_urchin": -0.009465143350088277,
      "inv_crown_of_thorns": -0.002669424228163267,
      "grazer_ratio": -0.00628433526639064,
      "impact_anchor": 0.0,
      "impact_nets": -0.0022730923504003997,
      "impact_trash": -0.007070225083601929,
      "impact_bleaching": 0.00046140194900651276,
      "impact_cot": -0.004160315877368911,
      "latitude": -0.010159796572629736,
      "longitude": 0.05955713498725778
    },
    "factor_diagnostics": [
      {
        "factor": "noaa_max_dhw",
        "analysis": "Spearman rank correlation",
        "n": 348,
        "statistic": -0.1045779727630862,
        "statistic_unit": "rho",
        "p_value": 0.051270888572376425,
        "caution": "Descriptive lagged association; not a causal effect"
      },
      {
        "factor": "noaa_mean_ssta",
        "analysis": "Spearman rank correlation",
        "n": 348,
        "statistic": -0.06056818930566387,
        "statistic_unit": "rho",
        "p_value": 0.2598039926898717,
        "caution": "Descriptive lagged association; not a causal effect"
      },
      {
        "factor": "grp_disturbance_indicators",
        "analysis": "Spearman rank correlation",
        "n": 338,
        "statistic": 0.07772612436258132,
        "statistic_unit": "rho",
        "p_value": 0.15391408226206862,
        "caution": "Descriptive lagged association; not a causal effect"
      },
      {
        "factor": "grp_pollution_indicators",
        "analysis": "Spearman rank correlation",
        "n": 338,
        "statistic": 0.14597611401784685,
        "statistic_unit": "rho",
        "p_value": 0.00718360745525168,
        "caution": "Descriptive lagged association; not a causal effect"
      },
      {
        "factor": "fish_parrotfish",
        "analysis": "Spearman rank correlation",
        "n": 348,
        "statistic": -0.0326674872877121,
        "statistic_unit": "rho",
        "p_value": 0.5436029873395897,
        "caution": "Descriptive lagged association; not a causal effect"
      },
      {
        "factor": "grazer_ratio",
        "analysis": "Spearman rank correlation",
        "n": 331,
        "statistic": -0.05970715805382468,
        "statistic_unit": "rho",
        "p_value": 0.27874907864012083,
        "caution": "Descriptive lagged association; not a causal effect"
      },
      {
        "factor": "impact_anchor",
        "analysis": "Mean difference: mentioned minus not mentioned",
        "n": 348,
        "statistic": 0.7535327329651386,
        "statistic_unit": "percentage points per year",
        "p_value": 0.6580050963797206,
        "caution": "Narrative mention comparison; absence may mean unreported"
      },
      {
        "factor": "impact_trash",
        "analysis": "Mean difference: mentioned minus not mentioned",
        "n": 348,
        "statistic": -0.3909071505171756,
        "statistic_unit": "percentage points per year",
        "p_value": 0.6040435948163754,
        "caution": "Narrative mention comparison; absence may mean unreported"
      },
      {
        "factor": "impact_bleaching",
        "analysis": "Mean difference: mentioned minus not mentioned",
        "n": 348,
        "statistic": 0.8710021173123366,
        "statistic_unit": "percentage points per year",
        "p_value": 0.5471291369752176,
        "caution": "Narrative mention comparison; absence may mean unreported"
      }
    ]
  },
  "validationByYear": [
    {
      "target_year": "2021",
      "n": "24",
      "mae": "5.699837958186007",
      "rmse": "7.580132511639961",
      "r2": "0.10698435283396346",
      "bias": "-2.4031913472193795"
    },
    {
      "target_year": "2022",
      "n": "35",
      "mae": "6.943627326142161",
      "rmse": "9.95500600929782",
      "r2": "0.11671892537391992",
      "bias": "-0.02610073128010702"
    },
    {
      "target_year": "2023",
      "n": "43",
      "mae": "5.75575686509108",
      "rmse": "7.239246743069443",
      "r2": "0.1784066636772661",
      "bias": "0.8746988044550557"
    },
    {
      "target_year": "2024",
      "n": "41",
      "mae": "5.600589599274473",
      "rmse": "7.061191062718651",
      "r2": "-0.2864765388207775",
      "bias": "2.2610978641627018"
    },
    {
      "target_year": "2025",
      "n": "40",
      "mae": "5.3833317053672",
      "rmse": "6.735009552131487",
      "r2": "-0.653635666315163",
      "bias": "4.451967459018678"
    }
  ],
  "tourismDataGap": {
    "source": "Jabatan Taman Laut Malaysia / data.gov.my",
    "verifiedCoverage": "2000-2009 aggregate context",
    "annualTrend": [
      {
        "year": 2000,
        "domestic": 180541,
        "foreign": 242688,
        "total": 423229
      },
      {
        "year": 2001,
        "domestic": 259204,
        "foreign": 224917,
        "total": 484121
      },
      {
        "year": 2002,
        "domestic": 267432,
        "foreign": 198155,
        "total": 465587
      },
      {
        "year": 2003,
        "domestic": 254637,
        "foreign": 126435,
        "total": 381072
      },
      {
        "year": 2004,
        "domestic": 356189,
        "foreign": 203673,
        "total": 559862
      },
      {
        "year": 2005,
        "domestic": 228480,
        "foreign": 201400,
        "total": 429880
      },
      {
        "year": 2006,
        "domestic": 265401,
        "foreign": 254614,
        "total": 520015
      },
      {
        "year": 2007,
        "domestic": 262670,
        "foreign": 215012,
        "total": 477682
      },
      {
        "year": 2008,
        "domestic": 318702,
        "foreign": 189786,
        "total": 508488
      },
      {
        "year": 2009,
        "domestic": 268780,
        "foreign": 261978,
        "total": 530758
      }
    ],
    "limitation": "No verified island-level exposure series; 2010-2017 local extension excluded"
  },
  "economicValuation": {
    "publication": "Total Economic Value of Marine Biodiversity: Malaysia Marine Parks",
    "publisher": "Department of Marine Park Malaysia",
    "study_period": "2011-2015",
    "evaluated_archipelagos": 6,
    "scope_note": "Published annual benchmark for six evaluated Malaysian marine-park archipelagos; not a current ReefSafe estimate",
    "reported_total_myr": 8700000000,
    "calculated_total_myr": 8686990000,
    "source_url": "https://wdpa.s3.amazonaws.com/Country_informations/MYS/TOTAL%20ECONOMIC%20VALUE%20OF%20MARINE%20BIODIVERSITY.pdf",
    "components": [
      {
        "component": "Aesthetic value",
        "annual_value_myr": 8000000000,
        "source_page": 9
      },
      {
        "component": "Fisheries",
        "annual_value_myr": 580400000,
        "source_page": 6
      },
      {
        "component": "Coastal protection",
        "annual_value_myr": 56250000,
        "source_page": 11
      },
      {
        "component": "Carbon sequestration",
        "annual_value_myr": 30240000,
        "source_page": 12
      },
      {
        "component": "Bequest value",
        "annual_value_myr": 14500000,
        "source_page": 13
      },
      {
        "component": "Tourism",
        "annual_value_myr": 4600000,
        "source_page": 7
      },
      {
        "component": "Biological support",
        "annual_value_myr": 1000000,
        "source_page": 10
      }
    ]
  }
};
window.TOURISM_DATA_GAP = window.REEFSAFE_DATA.tourismDataGap;
window.ECONOMIC_VALUATION = window.REEFSAFE_DATA.economicValuation;
