"""Build the browser dashboard data bundle from checked pipeline outputs."""

import csv
import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.economic_valuation import load_dmpm_tev


PROCESSED = ROOT / "data/processed"
DASHBOARD = ROOT / "dashboard"


def read_csv(path):
    with Path(path).open(encoding="utf-8", newline="") as stream:
        return list(csv.DictReader(stream))


def number(value, cast=float, default=0):
    return cast(value) if value not in (None, "") else default


def build_bundle():
    priorities = []
    for row in read_csv(PROCESSED / "reef_priority_predictions.csv"):
        priorities.append({
            "rank": int(row["priority_rank"]),
            "island": row["island"],
            "state": row["state"],
            "ecoregion": row["ecoregion"],
            "lat": float(row["latitude"]),
            "lng": float(row["longitude"]),
            "marinePark": row["marine_park"],
            "surveyYear": int(row["survey_year"]),
            "lcc": float(row["live_coral_cover_pct"]),
            "lccChangeRate": number(row["lcc_change_rate"]),
            "dhwContext": number(row["noaa_max_dhw"]),
            "predictedNextChange": float(row["predicted_next_change_pct_per_year"]),
            "predictionLower": float(row["prediction_lower"]),
            "predictionUpper": float(row["prediction_upper"]),
            "tier": row["priority_tier"],
            "sourceConfidence": row["confidence"],
            "evidence": row["evidence"],
            "nextStep": row["recommended_next_step"],
        })

    history = defaultdict(list)
    for row in read_csv(PROCESSED / "master_reef_tourism_dataset.csv"):
        if row["live_coral_cover_pct"]:
            history[row["island"]].append({
                "year": int(row["survey_year"]),
                "lcc": float(row["live_coral_cover_pct"]),
                "dhwContext": number(row.get("noaa_max_dhw")),
            })
    for rows in history.values():
        rows.sort(key=lambda item: item["year"])

    visitors = defaultdict(lambda: {"domestic": 0, "foreign": 0})
    for row in read_csv(ROOT / "data/raw/structured/taman_laut_visitors_2000_2017.csv"):
        year = int(row["year"])
        if year <= 2009:
            visitors[year]["domestic"] += int(row["domestic_visitors"])
            visitors[year]["foreign"] += int(row["foreign_visitors"])
    visitor_trend = [
        {"year": year, **values, "total": values["domestic"] + values["foreign"]}
        for year, values in sorted(visitors.items())
    ]

    metrics = json.loads((ROOT / "output/model_evaluation_metrics.json").read_text(encoding="utf-8"))
    paired = read_csv(PROCESSED / "paired_change_summary.csv")[0]
    latest_mean = sum(item["lcc"] for item in priorities) / len(priorities)

    return {
        "nationalKPIs": {
            "latestMeanCoralCover": latest_mean,
            "latestSurveyYear": max(item["surveyYear"] for item in priorities),
            "pairedChange2024To2025": float(paired["change_pp"]),
            "pairedUnits": int(paired["paired_units"]),
            "priorityCount": sum(item["tier"] == "High screening priority" for item in priorities),
            "surveyedUnits": len(priorities),
        },
        "priorityIslands": priorities,
        "islandHistory": dict(history),
        "factorRelationships": read_csv(PROCESSED / "factor_relationships.csv"),
        "heatSummary": read_csv(PROCESSED / "heat_category_summary.csv"),
        "modelMetrics": metrics,
        "validationByYear": read_csv(PROCESSED / "model_validation_by_year.csv"),
        "tourismDataGap": {
            "source": "Jabatan Taman Laut Malaysia / data.gov.my",
            "verifiedCoverage": "2000-2009 aggregate context",
            "annualTrend": visitor_trend,
            "limitation": "No verified island-level exposure series; 2010-2017 local extension excluded",
        },
        "economicValuation": load_dmpm_tev(),
    }


def main():
    bundle = build_bundle()
    payload = json.dumps(bundle, indent=2, ensure_ascii=False)
    output = (
        "// Auto-generated by scripts/build_web_dashboard_data.py\n"
        f"window.REEFSAFE_DATA = {payload};\n"
        "window.TOURISM_DATA_GAP = window.REEFSAFE_DATA.tourismDataGap;\n"
        "window.ECONOMIC_VALUATION = window.REEFSAFE_DATA.economicValuation;\n"
    )
    target = DASHBOARD / "data.js"
    target.write_text(output, encoding="utf-8")
    print(f"Built {target} with {len(bundle['priorityIslands'])} monitoring units")


if __name__ == "__main__":
    main()
